kind: pipeline
name: syntax-php7.0

steps:
  - name: syntax-php7.0
    image: nextcloudci/php7.0:php7.0-7
    commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude vendor/ .

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: syntax-php7.1

steps:
  - name: syntax-php7.1
    image: nextcloudci/php7.1:php7.1-11
    commands:
      - composer install
      - ./vendor/bin/parallel-lint --exclude vendor/ .

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
